### ISSUE TITLE
Publish v2.0.8

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/goingnative#89]
Hi @workshopper/deploy 

I updated the workshopper dependencies and fixes errors when compile solutions.

I would like to publish a new version, so people can get a working version of this workshopper.

Can you publish this new version ([v2.0.8](https://github.com/workshopper/goingnative/releases/tag/v2.0.8))?

cc @martinheidegger @julianduque @AnshulMalik

**Comment by rvagg** [comment]
That's a lot of work @ccarruitero! thanks for keeping on top of this.

Maybe we should consider an automated release process so we don't have individuals blocking releases when new folks show up and start doing good work. https://github.com/mikeal/merge-release would be good to consider. It just means we'd have to be very strict about who has merge access because that's essentially release access too.

**Comment by rvagg** [comment]
(I assume I still have npm owner on this package so I could release it but don't want to step on toes, I haven't been involved for some time. If there are no objections from other owners in the next day or so I can go ahead and get this out).

**Comment by martinheidegger** [comment]
@rvagg this should be fine.

**Comment by rvagg** [comment]
Published.

Lots of good work in here @ccarruitero. Some notes as I was reviewing the diff since the last release (mine, January 2016!).

* I assume `standard --fix` was used to help get the formatting wrangled. One problem that it doesn't handle well is converting single-line if, if/else, if/elseif/else's to braced versions. There's some funny looking very long lines, the best one is probably in exercises/mission_possible_part_three/exercise.js
* You should add yourself to credits.txt
* .jshintrc can go

Thanks for putting in the effort here so far, I'm sure it'll be appreciated.

**Comment by ccarruitero** [comment]
Hi @rvagg 

Thanks for publish the new version :tada:

I'll take a look into your comments about the changes. Specially into the `standard --fix` mess with `if/else ...`

Aside, not sure if you have access to publish `stream-adventure`?. I was looking to [publish a new version](https://github.com/workshopper/stream-adventure/issues/230) there too.

**Comment by rvagg** [comment]
It looks like @julianduque or @calvinmetcalf might be the best chances to get a stream-adventure published. Either of you two active and interested in continuing to help maintain it and other workshoppers, or at least be available for publishing?

I'd like to give @ccarruitero publish access to goingnative, any @workshopper/deploy folks object please let me know here or in private email.

**Comment by calvinmetcalf** [comment]
i can give somebody access to deploy stream-adventure

**Comment by ccarruitero** [comment]
Hi @calvinmetcalf,

I would like to have access to publish `stream-adventure`.
I was updating the `stream-adventure` workshopper and I was looking to [publish a new version](https://github.com/workshopper/stream-adventure/issues/230) since some weeks ago.

**Comment by rvagg** [comment]
@ccarruitero I'm assuming `ccarruitero` on npm is you. I've added you to goingnative, please take the responsibility seriously and make sure to do everything through this repo. Thanks for taking on this task!

**Comment by ccarruitero** [comment]
Thanks @rvagg , I'll do my best to accomplish with this task.

**Comment by calvinmetcalf** [comment]
thanks @rvagg got there before me

**Comment by rvagg** [comment]
@calvinmetcalf not for stream-adventure, I don't have owner access there so you'll need to do that

**Comment by calvinmetcalf** [comment]
all set @ccarruitero

**Comment by ccarruitero** [comment]
Thanks @calvinmetcalf
